# workflow name
name : First Workflow

# Event at which the workflow to be triggered
on  :  
  push: 
  workflow_dispatch:
jobs: 

  Hello-job:
  
    # runner
    runs-on: ubuntu-latest
    steps:
      - name : Hello World
        run : echo "Hello World"

      - name : Multi-line bash
        run : 
            echo  "I am" 
            echo  " a multi-line" 
            echo  " script" 

  echo-GoodBy:
    runs-on: ubuntu-slim
    steps:
      - name : Say GoodBye
        run : echo "GoodBye!:"    
        
      - name : Event Name
        run : 
            echo "Event name ${{github.event_name}} " 
            #Context variable
  windows-echo:
    if: github.event_name == 'push'
    run-on : windows_latest
    steps:
      - name: Show OS
        shell: bash
        run:
           echo "The job is running on an Windows runner"
